name = "angkringan-pos"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"

[[d1_databases]]
binding = "DB"
database_name = "angkringan-db"
database_id = "2486a8c1-372d-4d2a-b0f4-a11a3273cb6d"